---
# tasks file for vnc
- name: "Installing the vnc package"
  yum: pkg={{ item }} state=installed
  with_items:
    - tigervnc-server
    
- name: Ensure group "oracle" exists
  group:
    name: oracle
    state: present 

- name: Add the user 'oracle' with a bash shell, appending the group 'oracle' 
  user:
    name: oracle
    shell: /bin/bash
    groups: oracle
    home: /home/oracle    

- name: "Copying the vnc configuration file"
  copy: src=/home/developer/leaning/ansible/roles/vnc/files/vncserver@:1.service dest=/etc/systemd/system/vncserver@:1.service owner=root group=root mode=0644

- name: "Create the remote /root/.vnc directory"
  file:
    path: /root/.vnc
    mode: 0755
    state: directory

- name: "Generate vnc password for root user remotely"
  shell: |
    echo QaZwSx123 | vncpasswd -f > /root/.vnc/passwd

- name: "Change the permission to 600 for /root/.vnc/passwd file"
  file:
    path: /root/.vnc/passwd
    mode: 0600

- name: "Start & enable the vncserver"
  systemd:
    state: started
    daemon_reload: yes
    name: vncserver@:1
    enabled: True

- name: Allow new incoming  packets on TCP port 5901 (vnc).
  iptables:
    chain: IN_public_allow
    protocol: tcp
    destination_port: 5901
    ctstate: NEW
    jump: ACCEPT
    comment: Accept new VNC connections.    

- name: Allow new incoming  packets on TCP port 7001 (console WLS).
  iptables:
    chain: IN_public_allow
    protocol: tcp
    destination_port: 7001
    ctstate: NEW
    jump: ACCEPT
    comment: Accept new console connections.     